version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.2.1

workflows:
  test-build-deploy:
    jobs:
      - lint-charms:
          context: aws
      - build-and-deploy-charms-on-lxd:
          context: aws
          requires:
            - lint-charms
jobs:
  lint-charms:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Install tox
          command: |
            sudo apt-get update
            sudo apt-get install -y tox
      - run:
          command: |
            make lint
